Repository Hharshitsingh/blogApp, pull requests merged in 2022-10, with the labels that each got.

#2 Update about.jsx
  src/components/about/about.jsx
Labels: hactoberfest-accepted

#1 Update contact.jsx
  src/components/contact/contact.jsx
Labels: help wanted, hactoberfest-accepted

#3 Update data.js
  src/constants/data.js
Labels: good first issue, hactoberfest-accepted

#7 Update api.js
  src/service/api.js
Labels: enhancement, hactoberfest-accepted

#6 Update data.js
  src/constants/data.js
Labels: help wanted, hactoberfest-accepted

#5 Update header.jsx
  src/components/header/header.jsx
Labels: enhancement, hactoberfest-accepted
